In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('AppleStore.csv')
data.sample(5)

,Unnamed: 0,id,track_name,size_bytes,currency,price,rating_count_tot,rating_count_ver,user_rating,user_rating_ver,ver,cont_rating,prime_genre,sup_devices.num,ipadSc_urls.num,lang.num,vpp_lic
6009,8406,1108206682,Rise!,118787072,USD,0.00,18,14,3.5,3.5,4,4+,Games,38,5,1,1
1260,1465,516561342,"LINE Camera - Photo editor, Animated Stamp, Fi...",77113344,USD,0.00,3978,58,4.5,5.0,14.0.4,4+,Photo & Video,37,5,16,1
250,284,337462979,First Words Deluxe,63316992,USD,4.99,1101,8,4.0,4.0,7.0,4+,Games,38,5,1,1
2737,3265,888701288,Instaflash Pro,17196032,USD,4.99,249,79,5.0,5.0,4.0.1,4+,Photo & Video,37,5,2,1
2277,2658,735945527,Cut the Rope: Time Travel Free,122609664,USD,0.00,4327,1094,4.0,4.5,1.1.0,4+,Games,38,5,1,1

In [ ]:
data[['prime_genre','track_name']].head()

    prime_genre                                         track_name
0         Games                                    PAC-MAN Premium
1  Productivity                          Evernote - stay organized
2       Weather    WeatherBug - Local Weather, Radar, Maps, Alerts
3      Shopping  eBay: Best App to Buy, Sell, Save! Online Shop...
4     Reference                                              Bible

In [ ]:
data[['rating_count_tot','prime_genre']].groupby('prime_genre').sum().sort_values('rating_count_tot',ascending=False).head()

                   rating_count_tot
prime_genre
Games                      52878491
Social Networking           7598316
Photo & Video               5008946
Entertainment               4030518
Music                       3980199

In [ ]:
data[['track_name','prime_genre']].groupby('prime_genre').count().sort_values('track_name',ascending=False).head()

               track_name
prime_genre
Games                3862
Entertainment         535
Education             453
Photo & Video         349
Utilities             248

In [ ]:
data[['rating_count_tot','user_rating','track_name','prime_genre']].groupby(['track_name','prime_genre']).agg({'user_rating':'mean','rating_count_tot':'sum'}).sort_values('rating_count_tot',ascending=False).head(10)

                                           user_rating  rating_count_tot
track_name              prime_genre
Facebook                Social Networking          3.5           2974676
Instagram               Photo & Video              4.5           2161558
Clash of Clans          Games                      4.5           2130805
Temple Run              Games                      4.5           1724546
Pandora - Music & Radio Music                      4.0           1126879
Pinterest               Social Networking          4.5           1061624
Bible                   Reference                  4.5            985920
Candy Crush Saga        Games                      4.5            961794
Spotify Music           Music                      4.5            878563
Angry Birds             Games                      4.5            824451

In [ ]:
data[['track_name','user_rating','rating_count_tot','prime_genre','price']].groupby(['track_name','prime_genre']).agg({'user_rating':'mean','rating_count_tot':'sum','price':'mean'}).sort_values('price',ascending=False).head(10)

,,user_rating,rating_count_tot,price
track_name,prime_genre,,,
LAMP Words For Life,Education,4.0,41,299.99
Proloquo2Go - Symbol-based AAC,Education,4.0,773,249.99
KNFB Reader,Productivity,4.5,71,99.99
NAVIGON Europe,Navigation,3.5,927,74.99
Articulation Station Pro,Education,4.5,294,59.99
FineScanner Pro - PDF Document Scanner App + OCR,Business,4.0,100,59.99
Articulation Test Center Pro,Education,4.5,29,59.99
VPN Pro | Lifetime Proxy & Best VPN by Betternet,Business,4.5,207,49.99
Cubasis 2 - Mobile Music Creation System,Music,4.0,297,49.99
プチ・ロワイヤル仏和辞典（第4版）・和仏辞典（第3版）,Reference,0.0,0,47.99